apiVersion: v1
kind: Namespace
metadata:
  name: birthday-mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: birthday-mongodb
  labels:
    name: mongo
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: birthday-mongodb
spec:
  selector:
    matchLabels:
      role: mongo
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
    spec:
      containers:
      - name: mongodb-standalone
        image: mongo
        env:
          - name: MONGO_INITDB_DATABASE
            value: birthdays
        volumeMounts:
          - name: myclaim
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: myclaim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
